image: WMF 5
version: 1.0.0 (Build {build})

init:

clone_script:
  - ps: >-
      if ( -not $env:appveyor_pull_request_number ) {
        git clone -q --branch=$env:appveyor_repo_branch https://github.com/$env:appveyor_repo_name.git $env:appveyor_build_folder
        git checkout -qf $env:appveyor_repo_commit
        git submodule update -q --init --recursive
      } else {
        git clone -q https://github.com/$env:appveyor_repo_name.git $env:appveyor_build_folder
        git fetch -q origin +refs/pull/$env:appveyor_pull_request_number/merge:
        git checkout -qf FETCH_HEAD
        git submodule update -q --init --recursive
      }

install:
  - cmd: GitVersion /output buildserver
  - ps: .\install.ps1 -ErrorAction Stop -InformationAction Continue -Verbose

build_script:
  - cmd: make

test_script:
  - cmd: make test

before_deploy:
  - ps: >-
      & GitReleaseNotes . /OutputFile ReleaseNotes.md;
      ${env:release_description} = ( Get-Content -LiteralPath ReleaseNotes.md -Encoding UTF8 ) -join "`n";

deploy:
  - provider: Environment
    name: GitHub-Releases
    description: $(release_description)
    artifact: fonts, ttf, doc, ctan, msi
    on:
      branch: master
      #appveyor_repo_tag: true
  - provider: Environment
    name: Chocolatey
    artifact: choco.fonts.install
    on:
      branch: master
      #appveyor_repo_tag: true
