add_cus_dep('glo', 'gls', 0, 'run_makeglossaries');

sub run_makeglossaries {
  $q = $silent ? '-q' : '';
  system("makeindex $q -s gglo.ist -t $_[0].glg -o $_[0].gls $_[0].glo");
}

push @generated_exts, 'glo', 'gls', 'glg';
